version: '3'

services:
    db:
        build:
            context: ./backend/docker
            dockerfile: db.Dockerfile

        # keep in sync with .env
        ports:
            - '5432:5432'

        env_file: './backend/.env'

    web:
        depends_on:
            - db

        build:
            context: ./backend
            dockerfile: Dockerfile
        
        ports:
            - '3030:3030'
