version: '3'

networks:
    net:
       name: net

services:
    db:
        image: postgresql

        build:
            context: ./backend/docker
            dockerfile: db.Dockerfile

        # keep in sync with .env
        ports:
            - '5432:5432'

        env_file: './backend/.env'

        networks:
            - net

    web:
        image: nodeserver

        depends_on:
            - db

        build:
            context: ./backend
            dockerfile: Dockerfile
        
        ports:
            - '3030:3030'

        networks:
            - net
