version: '3'

networks:
    net:
        name: net

volumes:
    aica:

services:
    db:
        image: postgresql

        build:
            context: ./backend/docker
            dockerfile: db.Dockerfile

        # keep in sync with .env
        ports:
            - '5432:5432'

        env_file: '.db-env'

        networks:
            - net

        volumes:
            - aica:/home/node/app

    proxy:
        image: aiproxy

        build:
            context: ./../aalto-2022-proxy/
            dockerfile: Dockerfile

        ports:
            - '8080:8080'

        networks:
            - net

        env_file: './.proxy-env'

    web:
        image: nodeserver

        depends_on:
            - db
            - proxy

        build:
            context: ./
            dockerfile: ./backend/Dockerfile

        ports:
            - '3030:3030'

        networks:
            - net

        env_file: './.backend-env'
