version: '3'

services:
    db:
        build:
            context: ./docker
            dockerfile: db.Dockerfile

        # keep in sync with .env
        ports:
            - '5432:5432'

        env_file: '.env'
