name: CI

on:
    # Run on all branches
    push:

jobs:
    check:
        strategy:
            matrix:
                # https://nodejs.org/en/about/releases/
                # LTS: 18.x
                # Current: 19.x
                node-version: [18.x, 19.x]

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Root package.json should not have non-dev dependencies
              run: jq --exit-status 'has("dependencies") != true' < package.json

            - name: Setup project
              run: npm run setup-project

            - name: Check formatting
              run: npm run prettier

            - name: Check linters
              run: npm run lint-project

    test:
        strategy:
            matrix:
                # https://nodejs.org/en/about/releases/
                # LTS: 18.x
                # Current: 19.x
                node-version: [18.x, 19.x]
                os: [ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Setup project
              run: npm run setup-project

            - name: Build project
              run: npm run build-project

            - name: Run unit tests
              run: npm run test-project

            - name: Run end-to-end tests
              id: cypress
              run: npm run cypress-ci

            - name: Archive Cypress videos on fail
              uses: actions/upload-artifact@v3
              # Only upload artifacts if Cypress failed
              if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
              with:
                  name: cypress-videos
                  path: cypress/videos
