# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    # Run on all branches
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # https://nodejs.org/en/about/releases/
                # LTS: 18.x
                # Current: 19.x
                node-version: [18.x, 19.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm run setup-project
            - run: npm run prettier
            - run: npm run lint-project
            - run: npm run build-project
            - run: npm run test-project
            - name: Archive frontend build files
              uses: actions/upload-artifact@v3
              if: ${{ matrix.node-version  == '18.x' }}
              with:
                  name: build-frontend
                  path: frontend/build
                  retention-days: 7
            - name: Archive backend build files
              uses: actions/upload-artifact@v3
              if: ${{ matrix.node-version  == '18.x' }}
              with:
                  name: build-backend
                  path: backend/build
                  retention-days: 7
    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - run: exit 0
